[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "https://lead-tiet.netlify.app/*"
  to = "https://leadtiet.in/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
